# Generated by Django 5.0.6 on 2024-11-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('messagesubject', models.CharField(max_length=60)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
