# Generated by Django 5.0.6 on 2024-11-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Messages',
        ),
    ]
